name: Check

on:
  push:
    branches:
      - "main"
    tags-ignore:
      - "**"
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "**.md"

jobs:
  check:
    uses: TerakomariGandesblood/github-workflows/.github/workflows/python-check.yml@main
