name: Fmt

on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"

permissions:
  contents: read

jobs:
  fmt:
    name: Fmt
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4

      # https://github.com/sksat/setup-rye
      - uses: sksat/setup-rye@v0.7.0

      - name: Install dependencies
        run: rye sync --no-lock

      - name: Run black
        run: rye run black --check .

      - name: Install prettier
        run: npm install -g prettier

      - name: Run prettier
        run: prettier --check .
